// PERCORSO: src/main/webapp/app/config/font-awesome-icons.ts

import {
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faQrcode, // ← FIX: aggiunta per <fa-icon icon="qrcode"> in home.component.html
  faRoad,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  // jhipster-needle-add-icon-import
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faQrcode, // ← FIX: registrata nella libreria FA
  faRoad,
  faSave,
  faSearch,
  faSignOutAlt,
  faSignInAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  // jhipster-needle-add-icon-import
];
