package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AllergeneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergeneAllPropertiesEquals(Allergene expected, Allergene actual) {
        assertAllergeneAutoGeneratedPropertiesEquals(expected, actual);
        assertAllergeneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergeneAllUpdatablePropertiesEquals(Allergene expected, Allergene actual) {
        assertAllergeneUpdatableFieldsEquals(expected, actual);
        assertAllergeneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergeneAutoGeneratedPropertiesEquals(Allergene expected, Allergene actual) {
        assertThat(actual)
            .as("Verify Allergene auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergeneUpdatableFieldsEquals(Allergene expected, Allergene actual) {
        assertThat(actual)
            .as("Verify Allergene relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getNomeDefault()).as("check nomeDefault").isEqualTo(expected.getNomeDefault()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergeneUpdatableRelationshipsEquals(Allergene expected, Allergene actual) {
        assertThat(actual)
            .as("Verify Allergene relationships")
            .satisfies(a -> assertThat(a.getProdottis()).as("check prodottis").isEqualTo(expected.getProdottis()));
    }
}
