package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContattoItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContattoItemAllPropertiesEquals(ContattoItem expected, ContattoItem actual) {
        assertContattoItemAutoGeneratedPropertiesEquals(expected, actual);
        assertContattoItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContattoItemAllUpdatablePropertiesEquals(ContattoItem expected, ContattoItem actual) {
        assertContattoItemUpdatableFieldsEquals(expected, actual);
        assertContattoItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContattoItemAutoGeneratedPropertiesEquals(ContattoItem expected, ContattoItem actual) {
        assertThat(actual)
            .as("Verify ContattoItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContattoItemUpdatableFieldsEquals(ContattoItem expected, ContattoItem actual) {
        assertThat(actual)
            .as("Verify ContattoItem relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getValore()).as("check valore").isEqualTo(expected.getValore()))
            .satisfies(a -> assertThat(a.getEtichetta()).as("check etichetta").isEqualTo(expected.getEtichetta()))
            .satisfies(a -> assertThat(a.getOrdine()).as("check ordine").isEqualTo(expected.getOrdine()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContattoItemUpdatableRelationshipsEquals(ContattoItem expected, ContattoItem actual) {
        assertThat(actual)
            .as("Verify ContattoItem relationships")
            .satisfies(a -> assertThat(a.getLista()).as("check lista").isEqualTo(expected.getLista()));
    }
}
