package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ListaContattiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaContattiAllPropertiesEquals(ListaContatti expected, ListaContatti actual) {
        assertListaContattiAutoGeneratedPropertiesEquals(expected, actual);
        assertListaContattiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaContattiAllUpdatablePropertiesEquals(ListaContatti expected, ListaContatti actual) {
        assertListaContattiUpdatableFieldsEquals(expected, actual);
        assertListaContattiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaContattiAutoGeneratedPropertiesEquals(ListaContatti expected, ListaContatti actual) {
        assertThat(actual)
            .as("Verify ListaContatti auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaContattiUpdatableFieldsEquals(ListaContatti expected, ListaContatti actual) {
        assertThat(actual)
            .as("Verify ListaContatti relevant properties")
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListaContattiUpdatableRelationshipsEquals(ListaContatti expected, ListaContatti actual) {
        // empty method
    }
}
