package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuAllPropertiesEquals(Menu expected, Menu actual) {
        assertMenuAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuAllUpdatablePropertiesEquals(Menu expected, Menu actual) {
        assertMenuUpdatableFieldsEquals(expected, actual);
        assertMenuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuAutoGeneratedPropertiesEquals(Menu expected, Menu actual) {
        assertThat(actual)
            .as("Verify Menu auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuUpdatableFieldsEquals(Menu expected, Menu actual) {
        assertThat(actual)
            .as("Verify Menu relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescrizione()).as("check descrizione").isEqualTo(expected.getDescrizione()))
            .satisfies(a -> assertThat(a.getAttivo()).as("check attivo").isEqualTo(expected.getAttivo()))
            .satisfies(a -> assertThat(a.getLogo()).as("check logo").isEqualTo(expected.getLogo()))
            .satisfies(a -> assertThat(a.getLogoContentType()).as("check logo contenty type").isEqualTo(expected.getLogoContentType()))
            .satisfies(a -> assertThat(a.getLogoNome()).as("check logoNome").isEqualTo(expected.getLogoNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuUpdatableRelationshipsEquals(Menu expected, Menu actual) {
        assertThat(actual)
            .as("Verify Menu relationships")
            .satisfies(a -> assertThat(a.getContatti()).as("check contatti").isEqualTo(expected.getContatti()));
    }
}
