package main.domain;

import static main.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PiattoDelGiornoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPiattoDelGiornoAllPropertiesEquals(PiattoDelGiorno expected, PiattoDelGiorno actual) {
        assertPiattoDelGiornoAutoGeneratedPropertiesEquals(expected, actual);
        assertPiattoDelGiornoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPiattoDelGiornoAllUpdatablePropertiesEquals(PiattoDelGiorno expected, PiattoDelGiorno actual) {
        assertPiattoDelGiornoUpdatableFieldsEquals(expected, actual);
        assertPiattoDelGiornoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPiattoDelGiornoAutoGeneratedPropertiesEquals(PiattoDelGiorno expected, PiattoDelGiorno actual) {
        assertThat(actual)
            .as("Verify PiattoDelGiorno auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPiattoDelGiornoUpdatableFieldsEquals(PiattoDelGiorno expected, PiattoDelGiorno actual) {
        assertThat(actual)
            .as("Verify PiattoDelGiorno relevant properties")
            .satisfies(a -> assertThat(a.getAttivo()).as("check attivo").isEqualTo(expected.getAttivo()))
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescrizione()).as("check descrizione").isEqualTo(expected.getDescrizione()))
            .satisfies(a ->
                assertThat(a.getPrezzo()).as("check prezzo").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrezzo())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPiattoDelGiornoUpdatableRelationshipsEquals(PiattoDelGiorno expected, PiattoDelGiorno actual) {
        assertThat(actual)
            .as("Verify PiattoDelGiorno relationships")
            .satisfies(a -> assertThat(a.getMenu()).as("check menu").isEqualTo(expected.getMenu()))
            .satisfies(a -> assertThat(a.getProdotto()).as("check prodotto").isEqualTo(expected.getProdotto()));
    }
}
