package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PortataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortataAllPropertiesEquals(Portata expected, Portata actual) {
        assertPortataAutoGeneratedPropertiesEquals(expected, actual);
        assertPortataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortataAllUpdatablePropertiesEquals(Portata expected, Portata actual) {
        assertPortataUpdatableFieldsEquals(expected, actual);
        assertPortataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortataAutoGeneratedPropertiesEquals(Portata expected, Portata actual) {
        assertThat(actual)
            .as("Verify Portata auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortataUpdatableFieldsEquals(Portata expected, Portata actual) {
        assertThat(actual)
            .as("Verify Portata relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getNomeDefault()).as("check nomeDefault").isEqualTo(expected.getNomeDefault()))
            .satisfies(a -> assertThat(a.getNomePersonalizzato()).as("check nomePersonalizzato").isEqualTo(expected.getNomePersonalizzato())
            )
            .satisfies(a -> assertThat(a.getOrdine()).as("check ordine").isEqualTo(expected.getOrdine()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortataUpdatableRelationshipsEquals(Portata expected, Portata actual) {
        assertThat(actual)
            .as("Verify Portata relationships")
            .satisfies(a -> assertThat(a.getMenu()).as("check menu").isEqualTo(expected.getMenu()));
    }
}
