package main.domain;

import static main.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProdottoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdottoAllPropertiesEquals(Prodotto expected, Prodotto actual) {
        assertProdottoAutoGeneratedPropertiesEquals(expected, actual);
        assertProdottoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdottoAllUpdatablePropertiesEquals(Prodotto expected, Prodotto actual) {
        assertProdottoUpdatableFieldsEquals(expected, actual);
        assertProdottoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdottoAutoGeneratedPropertiesEquals(Prodotto expected, Prodotto actual) {
        assertThat(actual)
            .as("Verify Prodotto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdottoUpdatableFieldsEquals(Prodotto expected, Prodotto actual) {
        assertThat(actual)
            .as("Verify Prodotto relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescrizione()).as("check descrizione").isEqualTo(expected.getDescrizione()))
            .satisfies(a ->
                assertThat(a.getPrezzo()).as("check prezzo").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrezzo())
            )
            .satisfies(a -> assertThat(a.getVisibile()).as("check visibile").isEqualTo(expected.getVisibile()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdottoUpdatableRelationshipsEquals(Prodotto expected, Prodotto actual) {
        assertThat(actual)
            .as("Verify Prodotto relationships")
            .satisfies(a -> assertThat(a.getAllergenis()).as("check allergenis").isEqualTo(expected.getAllergenis()))
            .satisfies(a -> assertThat(a.getPortata()).as("check portata").isEqualTo(expected.getPortata()));
    }
}
