package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfiloRistoratoreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfiloRistoratoreAllPropertiesEquals(ProfiloRistoratore expected, ProfiloRistoratore actual) {
        assertProfiloRistoratoreAutoGeneratedPropertiesEquals(expected, actual);
        assertProfiloRistoratoreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfiloRistoratoreAllUpdatablePropertiesEquals(ProfiloRistoratore expected, ProfiloRistoratore actual) {
        assertProfiloRistoratoreUpdatableFieldsEquals(expected, actual);
        assertProfiloRistoratoreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfiloRistoratoreAutoGeneratedPropertiesEquals(ProfiloRistoratore expected, ProfiloRistoratore actual) {
        assertThat(actual)
            .as("Verify ProfiloRistoratore auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfiloRistoratoreUpdatableFieldsEquals(ProfiloRistoratore expected, ProfiloRistoratore actual) {
        assertThat(actual)
            .as("Verify ProfiloRistoratore relevant properties")
            .satisfies(a -> assertThat(a.getLivello()).as("check livello").isEqualTo(expected.getLivello()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfiloRistoratoreUpdatableRelationshipsEquals(ProfiloRistoratore expected, ProfiloRistoratore actual) {
        // empty method
    }
}
