package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TraduzioneMenuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraduzioneMenuAllPropertiesEquals(TraduzioneMenu expected, TraduzioneMenu actual) {
        assertTraduzioneMenuAutoGeneratedPropertiesEquals(expected, actual);
        assertTraduzioneMenuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraduzioneMenuAllUpdatablePropertiesEquals(TraduzioneMenu expected, TraduzioneMenu actual) {
        assertTraduzioneMenuUpdatableFieldsEquals(expected, actual);
        assertTraduzioneMenuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraduzioneMenuAutoGeneratedPropertiesEquals(TraduzioneMenu expected, TraduzioneMenu actual) {
        assertThat(actual)
            .as("Verify TraduzioneMenu auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraduzioneMenuUpdatableFieldsEquals(TraduzioneMenu expected, TraduzioneMenu actual) {
        assertThat(actual)
            .as("Verify TraduzioneMenu relevant properties")
            .satisfies(a -> assertThat(a.getLingua()).as("check lingua").isEqualTo(expected.getLingua()))
            .satisfies(a -> assertThat(a.getContenutoJson()).as("check contenutoJson").isEqualTo(expected.getContenutoJson()))
            .satisfies(a -> assertThat(a.getModificata()).as("check modificata").isEqualTo(expected.getModificata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraduzioneMenuUpdatableRelationshipsEquals(TraduzioneMenu expected, TraduzioneMenu actual) {
        assertThat(actual)
            .as("Verify TraduzioneMenu relationships")
            .satisfies(a -> assertThat(a.getMenu()).as("check menu").isEqualTo(expected.getMenu()));
    }
}
